# 6. Working with data

# Python -- Basic Codes

### Learning outcomes
- Understand how to access, create and update multi-dimensional data.
- Be able to use Python libraries.
- Have an introductory understanding of data frames and the library Pandas and NumPy.
- Be able to make use of the json data format.

## 1. Multi-dimensional data
Much of the data you will work with is multi-dimensional.
- Entities with multiple features - feature vectors
- Spreadsheets
- Databases - won’t discuss further here!
- Matrices

#### Reminder - Lists of Lists of Lists of . . .

In [1]:
warm = ['yellow', 'orange']
hot = ['red']
brightcolor = [warm]

brightcolor.append(hot)
print(brightcolor)

hot.append('pink')
print(hot)
print(brightcolor)

[['yellow', 'orange'], ['red']]
['red', 'pink']
[['yellow', 'orange'], ['red', 'pink']]


#### Accessing list of lists

In [2]:
type(warm) 

list

In [3]:
type(brightcolor) 

list

How do we access warm and hot from brightcolor?

In [4]:
print(brightcolor[0])

['yellow', 'orange']


In [5]:
print(brightcolor[1])

['red', 'pink']


#### Accessing individual entries

How do we access individual colours from brightcolor?

In [6]:
(brightcolor[0])[0]

'yellow'

In [7]:
(brightcolor[1])[1]

'pink'

#### Creating from scratch

In [8]:
brightcolor = [['yellow', 'orange'], ['red', 'pink']]
print(brightcolor[0][1])

orange


#### Updating

In [9]:
brightcolor[1][0] = 'white'
brightcolor[1].append('blue')
brightcolor.append(['grey','green','purple','mauve'])

In [10]:
brightcolor

[['yellow', 'orange'],
 ['white', 'pink', 'blue'],
 ['grey', 'green', 'purple', 'mauve']]

#### More complicated lists
- Could have more than list of lists
- Combine data types

In [11]:
B = [ ['yellow','orange'],(1,'Seven',True),{'area' : 924, 'population' : 201 }]
B

[['yellow', 'orange'], (1, 'Seven', True), {'area': 924, 'population': 201}]

#### Can do similar with dictionaries and tuples

In [12]:
countryData = { 'India' : { 'area' : 3287, 'population' : 1366}, \
 'Pakistan' : { 'area' : 908, 'population' : 217}, \
 'Nigeria' : { 'area' : 924, 'population' : 201}, \
 'China' : { 'area' : 9597, 'population' : 1434} }
countryData

{'India': {'area': 3287, 'population': 1366},
 'Pakistan': {'area': 908, 'population': 217},
 'Nigeria': {'area': 924, 'population': 201},
 'China': {'area': 9597, 'population': 1434}}

In [13]:
print(countryData['Nigeria']['population'])

201


### Quiz -- Multi-dimensional arrays

#### Question 1

In [14]:
# If the following python code has been run
A = [ [1,2,True], ["A","B",False]]
# then what is the output of
print(A[0][1])  

2


#### Question 2

In [15]:
# If the following python code has been run
A = [ [1,2,True], ["A","B",False]]
# then what is the output of
print(A[2][1])  
# It will create an index out of range error.

IndexError: list index out of range

#### Question 3

In [16]:
# If the following python code has been run
A = [ [1,2,True], ("A","B",False)]
# then what is the output of
print(A[1][2])  

False


#### Question 4

In [17]:
# If the following python code has been run
A = { "Square" : { "Side" : 5, "Area" : 25 }, "Circle" : { "Radius" : 3.0, "Area" : 9.4247778 } }  
# then how can you update the entry in A that has the value 3.0 to 4.0?

In [18]:
A['Circle']['Radius']

3.0

In [19]:
A['Circle']['Radius'] = 4.0
A['Circle']['Radius']

4.0

In [20]:
A

{'Square': {'Side': 5, 'Area': 25},
 'Circle': {'Radius': 4.0, 'Area': 9.4247778}}

### Importing libraries
- Python is based on a huge amount of software
- But there is more software that is out there for you to use that is not part of standard Python.
- There is a mechanism rather than pasting in code.
- Use libraries.
- Add them in your code using import command.

#### Example
- Generating random numbers is surprisingly useful in CS
- The library random does that.
- import random
- To reduce keypresses
- import random as rd

In [21]:
import random
n=random.randint(1,10)
n

5

In [22]:
import random as rd
n = rd.randint(1,10)
n

3

#### Technical note
- Depending on the environment you are using to run python you may need tools to install libraries
- Anaconda - gui
- Pip

## 2. Pandas
- Library for dealing with tables of data
- Call them 'data frames'
- A column of a DataFrame is called a Series
- DataFrames closely match structure of spreadsheets
- CSV (Comma Separated Values) files 

#### Reading in files

In [23]:
import pandas as pd
hits=pd.read_csv('msd_bb_matches.csv')

#### Summary of dataframe

In [24]:
type(hits)

pandas.core.frame.DataFrame

In [25]:
print(hits.head(4))

               msd_id        echo_nest_id                     artist  \
0  TRMMWJS12903CBB7F5  SOLBDWO12AB0188CC2                  Aerosmith   
1  TRMMCDR128F423AB03  SOSZNRJ12A8AE46E38  Michael Cera & Ellen Page   
2  TRMMRUB12903CA097C  SOGDEWJ12AB0184C06               Brook Benton   
3  TRMMFIS128E078EDEA  SOYURIX12A6701E960                  Aerosmith   

                            title  year  peak  weeks  
0  Remember (Walking In The Sand)  1979     6     67  
1             Anyone Else But You  2007     2     91  
2                       Lie To Me  1986    10     13  
3                          Cryin'  1993    26     12  


In [26]:
print(hits.tail(4))

                  msd_id        echo_nest_id               artist  \
5828  TRYYQHP128F9313D41  SORLBUJ12D02195076                 P!nk   
5829  TRYYIWA128EF347D8A  SOJROEQ12A67AD74A8              Donovan   
5830  TRYYNAO128E0793B81  SOHVHIK12A6D4F6192                 Styx   
5831  TRYYXQB12903D10BCC  SOGWHMA12AC468E230  Sir Douglas Quintet   

                    title  year  peak  weeks  
5828             Funhouse  2008    13     44  
5829     Jennifer Juniper  1968     9     26  
5830     Sing For The Day  1978     8     41  
5831  She's About A Mover  1969    12     13  


In [27]:
print(list(hits.columns))

['msd_id', 'echo_nest_id', 'artist', 'title', 'year', 'peak', 'weeks']


In [28]:
print(hits.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5832 entries, 0 to 5831
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   msd_id        5832 non-null   object
 1   echo_nest_id  5832 non-null   object
 2   artist        5832 non-null   object
 3   title         5832 non-null   object
 4   year          5832 non-null   int64 
 5   peak          5832 non-null   int64 
 6   weeks         5832 non-null   int64 
dtypes: int64(3), object(4)
memory usage: 319.1+ KB
None


In [29]:
print(hits.shape)

(5832, 7)


In [30]:
print(hits.dtypes)

msd_id          object
echo_nest_id    object
artist          object
title           object
year             int64
peak             int64
weeks            int64
dtype: object


#### Selecting columns

In [31]:
#Single column
msd = hits['msd_id']
msd

0       TRMMWJS12903CBB7F5
1       TRMMCDR128F423AB03
2       TRMMRUB12903CA097C
3       TRMMFIS128E078EDEA
4       TRMMNZH128F92CF7D0
               ...        
5827    TRYKULM128F425D2D4
5828    TRYYQHP128F9313D41
5829    TRYYIWA128EF347D8A
5830    TRYYNAO128E0793B81
5831    TRYYXQB12903D10BCC
Name: msd_id, Length: 5832, dtype: object

In [32]:
#Multiple columns
artistTitle = hits[['artist','title']]
artistTitle

artist                           title
0                     Aerosmith  Remember (Walking In The Sand)
1     Michael Cera & Ellen Page             Anyone Else But You
2                  Brook Benton                       Lie To Me
3                     Aerosmith                          Cryin'
4                  Buster Brown                      Sugar Babe
...                         ...                             ...
5827               John Fogerty               Eye Of The Zombie
5828                       P!nk                        Funhouse
5829                    Donovan                Jennifer Juniper
5830                       Styx                Sing For The Day
5831        Sir Douglas Quintet             She's About A Mover

[5832 rows x 2 columns]

#### Selecting rows

In [33]:
# Rows where the peak was less than 6
tops=hits[hits['peak'] < 6]
tops

msd_id        echo_nest_id                     artist  \
1     TRMMCDR128F423AB03  SOSZNRJ12A8AE46E38  Michael Cera & Ellen Page   
4     TRMMNZH128F92CF7D0  SOXCAWC12A8C144428               Buster Brown   
18    TRMWUXD128E0794FA9  SODKTBI12AF72A495A                      Sting   
21    TRMWOJA128F148C010  SOBMXKJ12A6D4F8297                       Onyx   
23    TRMWXEM128F429D851  SOYNWBC12A8C13E6AD      The Mamas & The Papas   
...                  ...                 ...                        ...   
5822  TRYXEQE128F42B2FFD  SOGMEKK12A8C13F38C            Sarah McLachlan   
5823  TRYXEWC128F1496088  SOTFLDB12A6D4FA89B               The Ronettes   
5824  TRYXVJO128F14A3A77  SOPOKQX12A6D4FC618              Bobbie Gentry   
5825  TRYKCYB128F4291982  SOOZIKI12A8C1397E3                    50 Cent   
5827  TRYKULM128F425D2D4  SOKDYBG12A8C136FA5               John Fogerty   

                          title  year  peak  weeks  
1           Anyone Else But You  2007     2     91  
4                    Sugar Babe  2002     2     99  
18       Englishman In New York  1987     4     84  
21                Throw Ya Gunz  1993     3     81  
23           Do You Wanna Dance  1966     5     76  
...                         ...   ...   ...    ...  
5822                      River  2006     3     71  
5823                Sleigh Ride  1963     2     33  
5824  Okolona River Bottom Band  1968     4     54  
5825       Straight To The Bank  2007     3     32  
5827          Eye Of The Zombie  1986     4     81  

[720 rows x 7 columns]

### Cleaning up data

In [34]:
# Can remove rows where data is missing
# (Primate data set - many NaNs)
import pandas as np
masses = pd.read_csv('BodyMass_.csv', encoding='ISO-8859-1')
noNA = masses[masses['BodyMassFemale_kg'].notna()]
noNA

Family           Genus                    CommonName  \
0    Cercopithecidae  Allenopithecus          Allen_s_Swamp_Monkey   
2     Cheirogaleidae       Allocebus       Hairy_eared_Dwarf_Lemur   
4    Cercopithecidae   Allochrocebus              L_Hoest_s_Monkey   
6    Cercopithecidae   Allochrocebus               Preuss_s_Monkey   
8    Cercopithecidae   Allochrocebus             Sun_tailed_Monkey   
..               ...             ...                           ...   
619  Cercopithecidae  Trachypithecus               Phayre_s_Langur   
620  Cercopithecidae  Trachypithecus                 Capped_Langur   
621  Cercopithecidae  Trachypithecus                 Cat_Ba_Langur   
625        Lemuridae         Varecia              Red_Ruffed_Lemur   
627        Lemuridae         Varecia  Black_and_white_Ruffed_Lemur   

                          Species                Species (ITIS)  BodyMass_kg  \
0     Allenopithecus_nigroviridis   Allenopithecus_nigroviridis         4.65   
2             Allocebus_trichotis           Allocebus_trichotis         0.08   
4           Allochrocebus_lhoesti         Allochrocebus_lhoesti         5.00   
6           Allochrocebus_preussi         Allochrocebus_preussi         3.80   
8           Allochrocebus_solatus         Allochrocebus_solatus         5.40   
..                            ...                           ...          ...   
619        Trachypithecus_phayrei        Trachypithecus_phayrei         7.44   
620       Trachypithecus_pileatus       Trachypithecus_pileatus        10.93   
621  Trachypithecus_poliocephalus  Trachypithecus_poliocephalus         8.05   
625                 Varecia_rubra                 Varecia_rubra         3.51   
627             Varecia_variegata             Varecia_variegata         3.58   

     BodyMassMale_kg  BodyMassFemale_kg Refs1  
0              6.130              3.180   210  
2              0.092              0.084   315  
4              7.000              3.000   155  
6              4.700              2.900   333  
8              6.890              3.920   326  
..               ...                ...   ...  
619            7.930              6.950   312  
620           12.000              9.860   210  
621            8.750              7.350  1134  
625            3.550              3.470   290  
627            3.630              3.520   285  

[370 rows x 9 columns]

#### Selecting rows and columns

In [35]:
# List Artist and Title when the year is 2007
aT2007 = hits.loc[hits['year'] == 2007, ['artist','title']] 
aT2007

artist                       title
1     Michael Cera & Ellen Page         Anyone Else But You
28               Britney Spears               Break The Ice
53                   Kanye West                    Stronger
58               Ashley Tisdale            He Said She Said
197                      Juanes                  Me Enamora
...                         ...                         ...
5391               Brad Paisley             I'm Still A Guy
5537                 The Elgins  It's Been A Long Long Time
5705                 Gary Allan        Learning How To Bend
5794          The White Stripes                  Icky Thump
5825                    50 Cent        Straight To The Bank

[114 rows x 2 columns]

In [36]:
# Can also use indices
aT = hits.iloc[5:100,3:5]
aT

title  year
5            Help Is On Its Way  1980
6                After Midnight  1970
7         Walk On The Wild Side  1972
8            Redneck Yacht Club  2005
9       Don't Leave Me This Way  1976
..                          ...   ...
95              What Kinda Gone  2008
96  What Am I Gonna Do With You  1975
97                     Juicebox  2005
98  Europa And The Pirate Twins  1982
99  I'll Never Break Your Heart  1996

[95 rows x 2 columns]

#### Quiz -- Pandas

In [37]:
# Question 1

# Suppose I have the following dataframe (called df)

#                       Name  Age     Sex
#0   Braund, Mr. Owen Harris   22    male
#1  Allen, Mr. William Henry   35    male
#2  Bonnell, Miss. Elizabeth   58  female
# How do I create a DataFrame with just the Age and Sex?
d = {'Name': ['Braund, Mr. Owen Harris', 'Allen, Mr. William Henry', 'Bonnell, Miss. Elizabeth'], 
                            'Age':[22, 35, 58], 'Sex': ['male', 'male', 'female']}
df = pd.DataFrame(data=d)
df

Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [38]:
# # How do I create a DataFrame with just the Age and Sex?
#df["Age","Sex"]
#df("Age","Sex")
#df == ["Age","Sex"]
df[["Age","Sex"]]

Age     Sex
0   22    male
1   35    male
2   58  female

In [39]:
# Question 2
# How do I select all the rows where the Sex is male?
#df["Sex"] == "male"
#df == "male"
#df["male"]
df[df["Sex"] == "male"]

Name  Age   Sex
0   Braund, Mr. Owen Harris   22  male
1  Allen, Mr. William Henry   35  male

#### Summary statistics
- Can compute max, min, mean, median, … of columns

In [40]:
print(hits[['year','peak']].median())

year    1987.0
peak      13.0
dtype: float64


In [41]:
# For full statistical description
print(hits[['year','peak']].describe())

              year         peak
count  5832.000000  5832.000000
mean   1985.966907    15.299040
std      13.979593    13.065922
min    1942.000000     2.000000
25%    1974.000000     8.000000
50%    1987.000000    13.000000
75%    1998.000000    19.000000
max    2010.000000   100.000000


In [42]:
# Save to file
aT2007.to_csv("aT2007.csv")

## 3. Numpy
- DataFrames allow different data types in each cell. 
- If we only allow integers/floats then DataFrame is a Matrix
- Tools of linear algebra to make use of
- Separate library numpy

In [44]:
import numpy as np
# Convert DataFrame to Numpy array
numbers = hits[['year', 'peak', 'weeks']]
hitData = numbers.to_numpy()
print(hitData)

[[1979    6   67]
 [2007    2   91]
 [1986   10   13]
 ...
 [1968    9   26]
 [1978    8   41]
 [1969   12   13]]


In [45]:
print(hitData.shape)

(5832, 3)


#### Converting back

In [46]:
A = pd.DataFrame(hitData)
# No column data
A = pd.DataFrame(hitData, columns=['year','peak','weeks'])
A

year  peak  weeks
0     1979     6     67
1     2007     2     91
2     1986    10     13
3     1993    26     12
4     2002     2     99
...    ...   ...    ...
5827  1986     4     81
5828  2008    13     44
5829  1968     9     26
5830  1978     8     41
5831  1969    12     13

[5832 rows x 3 columns]

In [48]:
# (Like DataFrames) can build arrays from scratch
A = np.array([[1.0,2.0,3.0],[-1.0,1.0,3.0]])
A

array([[ 1.,  2.,  3.],
       [-1.,  1.,  3.]])

In [49]:
# One dimensional arrays (vectors)
v = np.array([1.5,-2.0,-1.9]) 
v

array([ 1.5, -2. , -1.9])

#### Operations

In [50]:
# Can do scalar multiplication
A = A * 3.0
B = A + A
C = A - 1.0
C

array([[ 2.,  5.,  8.],
       [-4.,  2.,  8.]])

In [51]:
#Can do matrix-vector multiplication
A.dot(v)

array([-24.6, -27.6])

In [53]:
# Matrix transpose
hDT = hitData.transpose()
hDT

array([[1979, 2007, 1986, ..., 1968, 1978, 1969],
       [   6,    2,   10, ...,    9,    8,   12],
       [  67,   91,   13, ...,   26,   41,   13]], dtype=int64)

In [54]:
# Matrix-matrix multiplication
Hsq= hDT.dot(hitData)
Hsq

array([[23002924029,   177416002,   415992178],
       [  177416002,     2360500,     2871070],
       [  415992178,     2871070,    12553321]], dtype=int64)

#### Linear algebra

Sub-library numpy.linalg

Linear algebra operations
- Eigen-values
- SVD

#### Example

In [55]:
# Singular Value Decomposition
X = np.linalg.svd(hDT)
print(X)

(array([[-0.99980672,  0.01738404,  0.00918232],
       [-0.00771134,  0.08287014, -0.99653052],
       [-0.01808466, -0.99640872, -0.08272007]]), array([151696.46317611,   2248.74414242,    981.86538839]), array([[-1.30515597e-02, -1.32387610e-02, -1.30914612e-02, ...,
        -1.29743251e-02, -1.30419709e-02, -1.29795186e-02],
       [-1.41675329e-02, -2.47327797e-02,  9.96115233e-03, ...,
         4.02490735e-03, -2.58107343e-03,  9.90343641e-03],
       [ 6.77321348e-03,  9.07286203e-03,  7.32831815e-03, ...,
         7.07969732e-03,  6.92443433e-03,  5.13946364e-03],
       ...,
       [-1.28104755e-02, -6.09905221e-03, -5.76601252e-03, ...,
         9.99769631e-01, -2.01766970e-04, -2.42309531e-04],
       [-1.30374214e-02, -7.36039005e-03,  7.18553283e-04, ...,
        -2.05068680e-04,  9.99780481e-01, -1.78954433e-04],
       [-1.26927201e-02, -2.94712505e-03, -1.10944791e-02, ...,
        -2.39388607e-04, -1.73093187e-04,  9.99711074e-01]]))


In [57]:
Y = np.linalg.eig(A.dot(A.transpose()))
Y

(array([203.50686787,  21.49313213]),
 array([[ 0.75774021, -0.65255634],
        [ 0.65255634,  0.75774021]]))

In [66]:
# Variation on import statement
#from numpy import lining
from scipy import linalg
Y = linalg.eig(A.dot(A.transpose()))  
Y

(array([203.50686787+0.j,  21.49313213+0.j]),
 array([[ 0.75774021, -0.65255634],
        [ 0.65255634,  0.75774021]]))

#### Quiz -- Numpy
#### Question 1

Write a function matrixVectorMult which accepts two arguments - a NumPy matrix M and a Numpy vector v.
matrixVectorMult returns the vector corresponding to M v. matrixVectorMult should check if
- M is a two dimensional matrix
- v is a one dimensional vector
- M and v have the right dimensions to be multipled together
(hint use the shape command).
If it does not satisfy the requirements then it should return the string "Error!".

If

M=(1 3 
   
   2 4)

and

v=(−1 

1)

then 

matrixVectorMult(M,v) returns a Numpy matrix corresponding to

(−1 

−1) .

matrixVectorMult(v,M) and matrixVectorMult(v,v) return "Error!"

In [160]:
M = np.array([[1,2],[3,4]])
v = np.array([[1], [-1]])
print("M = ", M)
print("v = ", v)

M =  [[1 2]
 [3 4]]
v =  [[ 1]
 [-1]]


In [161]:
M.dot(v)

array([[-1],
       [-1]])

In [162]:
#v.transpose()
#v

In [163]:
print("M.shape = ", M.shape)
print("v.shape = ", v.shape)

M.shape =  (2, 2)
v.shape =  (2, 1)


In [164]:
print("M.shape[1] = ", M.shape[1])
print("v.shape[0] = ", v.shape[0])
print("v.shape[1] = ", v.shape[1])

M.shape[1] =  2
v.shape[0] =  2
v.shape[1] =  1


In [184]:
def matrixVectorMult(M, v):
    if M.shape[0]==2 & M.shape[1] == 2:
        if v.shape[0] == 2:
            if M.shape[1] == v.shape[0]:
                #v.transpose()
                return (M.dot(v))
            else:
                  print("ErrOR!")
   
            
        
M = np.array([[1,2],[3,4]])
v = np.array([1,-1])
#v = np.array([[1], [-1]])
print(matrixVectorMult(M,v))
#print(matrixVectorMult(v,M))
#print(matrixVectorMult(v,v))

[-1 -1]


IndexError: tuple index out of range

## 4. Json
- So far - regular data structures
- But what about data structures that are not regular
- Dictionaries?
- JSON (JavaScript Object Notation) designed for lightweight storage/reading such structures.

#### Saving

In [4]:
import json
myD = { 'red' : (0,1,0), 'green' : 'hello', 'blue' : 
[-1,2.0] }
fn= "myD.json"
fp= open(fn,'w')
json.dump(myD,fp)
fp.close()

#### Loading

In [9]:
fn = 'myD.json'
fp = open(fn)
X = json.load(fp)
fp.close()